/* ============================================================
   Project: Category Contribution to Overall Sales Analysis

   Objective:
   Analyze product categories to determine which category
   contributes the highest share of total business sales.

   Analysis Includes:
   1. Total Sales by Product Category
      - Calculate total revenue generated by each category

   2. Overall Business Sales Calculation
      - Compute total company-wide sales across all categories

   3. Percentage Contribution Analysis
      - Measure each category’s contribution percentage
        to total overall sales

   4. Category Ranking
      - Rank categories from highest to lowest sales contribution


   Dataset:
   - gold.facts_sales
   - gold.dim_products
============================================================ */



-- category that contributae the most overall sale : 



with cte_totall_category_sales as (

select

d.category ,
sum (f.sales_amount ) as totall_sales_by_category

from gold.facts_sales as f
left join gold.dim_products as d
on f.product_key = d.product_key

group by d.category

)


select
category ,
totall_sales_by_category ,
sum ( totall_sales_by_category ) over()  as totall_overall_sale ,

concat (round ( cast (totall_sales_by_category as float ) 
/ sum ( totall_sales_by_category ) over() *100.0 , 2) , '%') as tottall_percentage 


from cte_totall_category_sales
order by totall_sales_by_category desc
